export const selfData = {
  name: "Nguyen Hoang",
  first_name: "Hoang",
  last_name: "Nguyen",
  jobTitle: "Student",
  workFor: "KIIT University",
  current_location: {
    city: "Ha Nam",
    state: "Phu Ly",
    country: "Viet Nam",
  },
  DOB: {
    dd: 28,
    mm: 2,
    yyyy: 2007,
  },
  email: "hoang123091@gmail.com",
  roles: [
    "Chief Problem Solver",
    "Idea Mechanic",
    "Possibility Pilot",
    "Chaos Coordinator",
    "Chief Tinkerer",
    "Glitch Gladiator",
    "Solution Sorcerer",
    "Joyful Juggler",
  ],
  desc: "I design and build tools that live on the internet.",
  bio: "I'm a student Control Engineering and Automation passionate. I love studying new things, exploring new technologies, and turning creative ideas into accessible tools.",
  about: [
    "Hi, I'm a student Control Engineering and Automation.",
    "You can also call me Chaos",
    "Thank for ",
  ],

  socials_username: {
    facebook: "zzcwc",
    github: "aarabii",
    instagram: "aarab.ii",
    leetcode: "aarabii",
    linkedin: "aarab-nishchal",
    snapchat: "aarab.ii",
    telegram: "aarab_ii",
    twitter: "aarab_ii",
  },
};
