export const selfData = {
  name: "Nguyen Hoang",
  first_name: "Hoang",
  last_name: "Nguyen",
  jobTitle: "Student",
  workFor: "Hanoi University of Industry",
  current_location: {
    city: "Ha Nam",
    state: "Phu Ly",
    country: "Viet Nam",
  },
  DOB: {
    dd: 28,
    mm: 2,
    yyyy: 2007,
  },
  email: "hoang123091@gmail.com",
  roles: [
    "Chaos",
    "Idea Mechanic",
    "Possibility Pilot",
    "Chaos Coordinator",
    "Chief Tinkerer",
    "Glitch Gladiator",
    "Solution Sorcerer",
    "Joyful Juggler",
  ],
  desc: "I design and build tools that live on the internet.",
  bio: "I'm a student of Control Engineering and Automation passionate. I love studying new things, exploring new technologies, and turning creative ideas into accessible tools.",
  about: [
    "Hi, I'm a student of Control Engineering and Automation.",
    "You can also call me Chaos",
    "Thank for ",
  ],

  socials_username: {
    facebook: "worldismine091",
    github: "HoangNoPro",
    instagram: " ",
    leetcode: " ",
    linkedin: " ",
    snapchat: " ",
    telegram: "hoag091",
    twitter: "wordldismine091",
  },
};
